# Generated by Django 3.2 on 2021-05-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classof',
            field=models.CharField(blank=True, max_length=50, verbose_name='school'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=50, verbose_name='school'),
        ),
    ]
