# Generated by Django 3.2 on 2021-05-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210509_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classof',
            field=models.CharField(blank=True, max_length=50, verbose_name='class'),
        ),
    ]
