# Generated by Django 3.2 on 2021-05-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
