# Generated by Django 3.2 on 2021-05-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_video_book_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Китеп', 'verbose_name_plural': 'Китептер'},
        ),
    ]
